apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grpc-server
  labels:
    app: grpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          # Note that image is modified by skaffold or sync-script
          # to use a correct tag.
          image: "grpc-server"
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "9090"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: grpc
              containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-server-headless
  labels:
    app: grpc-server
spec:
  type: ClusterIP
  clusterIP: None # Note: this is important.
  ports:
    - port: 9090
      name: grpc
      targetPort: grpc
  selector:
    app: grpc-server
